<a href="https://colab.research.google.com/github/A-ghori/sklearn/blob/recovery/Mean_Median.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [6]:
import random
df = pd.read_csv("/content/Titanic-Dataset.csv",usecols=["Age","Fare","Survived"])
values = [
    random.choice([0,1])
    for _ in range(len(df))
]
df["Family"] = values

In [7]:
df.head(2)

   Survived   Age     Fare  Family
0         0  22.0   7.2500       1
1         1  38.0  71.2833       1

In [8]:
## Adding 5% NaN in Fare
n = int(len(df) * 0.05)

indices = np.random.choice(df.index, n , replace=False)
df.loc[indices, 'Fare'] = np.nan

In [9]:
df.isnull().mean()

Survived    0.000000
Age         0.198653
Fare        0.049383
Family      0.000000
dtype: float64

In [10]:
X = df.iloc[:, 1:]
y = df.iloc[:, 0]
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)
X_train.shape

(712, 3)

In [12]:
X_test.shape

(179, 3)

In [13]:
X_train.isnull().mean()

Age       0.196629
Fare      0.054775
Family    0.000000
dtype: float64

In [14]:
mean_age = X_train['Age'].mean()
median_age = X_train['Age'].median()

mean_fare = X_train['Fare'].mean()
medain_fare = X_train['Fare'].median()

mean_age, median_age , mean_fare, medain_fare

(np.float64(29.498846153846156), 28.0, np.float64(32.22588469539376), 14.4)

In [15]:
X_train['Age_mean'] = X_train['Age'].fillna(mean_age)
X_train['Age_median'] = X_train['Age'].fillna(median_age)

X_train['Fare_mean'] = X_train['Fare'].fillna(mean_fare)
X_train['Fare_median'] = X_train['Fare'].fillna(medain_fare)

X_train.sample(5)

      Age     Fare  Family  Age_mean  Age_median  Fare_mean  Fare_median
717  27.0  10.5000       1      27.0        27.0    10.5000      10.5000
479   2.0  12.2875       0       2.0         2.0    12.2875      12.2875
453  49.0  89.1042       1      49.0        49.0    89.1042      89.1042
50    7.0  39.6875       1       7.0         7.0    39.6875      39.6875
500  17.0   8.6625       1      17.0        17.0     8.6625       8.6625

In [16]:
print("Orginal Age Variable Variance:", X_train['Age'].var())
print("Orginal Variance after median imputation:", X_train['Age_median'].var())
print("Orginal Variance after mean imputation:", X_train['Age_mean'].var())


print("Orginal Fare Variable Variance:", X_train['Fare'].var())
print("Orginal Variance Fare after median imputation:", X_train['Fare_mean'].var())
print("Orginal Variance Fare after median imputation:", X_train['Fare_median'].var())

Orginal Age Variable Variance: 210.2517072477438
Orginal Variance after median imputation: 169.20731007048096
Orginal Variance after mean imputation: 168.8519336687225
Orginal Fare Variable Variance: 2691.8873148937078
Orginal Variance Fare after median imputation: 2544.231048675909
Orginal Variance Fare after median imputation: 2560.7063081405504

In [17]:
X_train.cov()

,Age,Fare,Family,Age_mean,Age_median,Fare_mean,Fare_median
Age,210.251707,66.686766,-0.421169,210.251707,210.251707,63.432892,62.841261
Fare,66.686766,2691.887315,-0.456200,53.899079,57.582146,2691.887315,2691.887315
Family,-0.421169,-0.456200,0.250154,-0.338238,-0.331985,-0.431177,-0.379836
Age_mean,210.251707,53.899079,-0.338238,168.851934,168.851934,50.942589,50.467454
Age_median,210.251707,57.582146,-0.331985,168.851934,169.207310,54.423631,54.111266
Fare_mean,63.432892,2691.887315,-0.431177,50.942589,54.423631,2544.231049,2544.231049
Fare_median,62.841261,2691.887315,-0.379836,50.467454,54.111266,2544.231049,2560.706308

In [21]:
X_train.corr()
#+1  → perfectly same direction
#0  → linear relationship nahi
#-1  → perfectly opposite direction
#Age vs Fare
#Age ↔ Fare = 0.0825
#
#Ye positive hai, lekin bahut close to 0 hai.
#
#Matlab:
#
#Age badhne par Fare bhi badhne ki halki si tendency hai, but relationship bahut weak hai.
#
#So practically:
#
#Age ───────── Fare
#       very weak

,Age,Fare,Family,Age_mean,Age_median,Fare_mean,Fare_median
Age,1.000000,0.082508,-0.058084,1.000000,1.000000,0.080378,0.079372
Fare,0.082508,1.000000,-0.017583,0.079651,0.085011,1.000000,1.000000
Family,-0.058084,-0.017583,1.000000,-0.052043,-0.051028,-0.017091,-0.015008
Age_mean,1.000000,0.079651,-0.052043,1.000000,0.998949,0.077723,0.076750
Age_median,1.000000,0.085011,-0.051028,0.998949,1.000000,0.082947,0.082205
Fare_mean,0.080378,1.000000,-0.017091,0.077723,0.082947,1.000000,0.996778
Fare_median,0.079372,1.000000,-0.015008,0.076750,0.082205,0.996778,1.000000