<a href="https://colab.research.google.com/github/A-ghori/sklearn/blob/main/One_Hot_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/cars.csv')
df.shape
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [48]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [49]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

## OneHotEncoding using Pandas

In [50]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

In [51]:
df['brand'].shape

(8128,)

## K-1 OneEncoding using SKLEARN using this drop first column from each categories categories mean Fuel and Owner are two catgeories and in these two categ we have more rows

In [52]:
result = pd.get_dummies(df,columns=['fuel', 'owner'], drop_first=True)
result.head()

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False

## OneHot Encoding using sklearn

In [53]:
X = df.drop('selling_price', axis=1)
y = df['selling_price']

from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)
X_train

         brand  km_driven    fuel                 owner
6518      Tata       2560  Petrol           First Owner
6144     Honda      80000  Petrol          Second Owner
6381   Hyundai     150000  Diesel  Fourth & Above Owner
438     Maruti     120000  Diesel          Second Owner
5939    Maruti      25000  Petrol           First Owner
...        ...        ...     ...                   ...
5226  Mahindra     120000  Diesel           First Owner
5390    Maruti      80000  Diesel          Second Owner
860    Hyundai      35000  Petrol           First Owner
7603    Maruti      27000  Diesel           First Owner
7270    Maruti      70000  Petrol          Second Owner

[6502 rows x 4 columns]

In [54]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first')

# fit() ka kaam hai categories ko learn karna.
# transform() actual encoding karta hai

X_train_new = ohe.fit_transform(X_train[['fuel', 'owner']]).toarray()
X_test_new = ohe.transform(X_test[['fuel','owner']]).toarray()
print(X_train_new)
X_train_new.shape

[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 1. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 1. 0. 0.]]

(6502, 7)

In [55]:
np.hstack((X_train[['brand', 'km_driven']].values, X_train_new)) # hstack = Horizontal Stack.
#Simple language mein:
#Arrays/DataFrames ko side-by-side horizontally jodna.

array([['Tata', 2560, 0.0, ..., 0.0, 0.0, 0.0],
       ['Honda', 80000, 0.0, ..., 1.0, 0.0, 0.0],
       ['Hyundai', 150000, 1.0, ..., 0.0, 0.0, 0.0],
       ...,
       ['Hyundai', 35000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 27000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 70000, 0.0, ..., 1.0, 0.0, 0.0]], dtype=object)

# OneHotEncoding with Top Categories

In [56]:
counts = df['brand'].value_counts()
print(counts)

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [59]:
# SO I take a threshold 100 means if any car companies are above 100 we consider those car companies as other categories means only skoda is seperated categories and after skoda the rest of the brands become other categories
df['brand'].nunique()
threshold = 100

lower_grade = counts[counts <= threshold]
print(lower_grade)

brand
Nissan           81
Jaguar           71
Volvo            67
Datsun           65
Mercedes-Benz    54
Fiat             47
Audi             40
Lexus            34
Jeep             31
Mitsubishi       14
Land              6
Force             6
Isuzu             5
Ambassador        4
Kia               4
MG                3
Daewoo            3
Ashok             1
Opel              1
Peugeot           1
Name: count, dtype: int64

In [58]:
pd.get_dummies(df['brand'].replace(lower_grade, 'others'))

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,others
0,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,False,True,False,False,False,False,False,False,False,False
8124,False,False,False,False,True,False,False,False,False,False,False,False,False
8125,False,False,False,False,False,False,True,False,False,False,False,False,False
8126,False,False,False,False,False,False,False,False,False,True,False,False,False
8127,False,False,False,False,False,False,False,False,False,True,False,False,False