<a href="https://colab.research.google.com/github/A-ghori/sklearn/blob/main/Ordinal_Encoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [30]:
df = pd.read_csv("/content/ordinal_regression_dataset.csv")
df.head()

   Feature1  Feature2  Feature3  Rating
0 -0.828995  4.874642 -1.621506  Medium
1 -0.560181  6.910285 -2.461083    High
2  0.747294  3.028548 -1.565197     Low
3  0.610370  6.008093 -1.322181    High
4 -0.020902  3.939485 -1.793283  Medium

In [31]:
df.drop(
    columns=["Feature1", "Feature2", "Feature3"],
    inplace=True
)

In [33]:
df.tail()

     Rating
145  Medium
146  Medium
147     Low
148  Medium
149  Medium

In [37]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[["Low", "Medium", "High"]])
print(oe)
df[["Rating"]] = oe.fit_transform(df[["Rating"]])

df.head()

OrdinalEncoder(categories=[['Low', 'Medium', 'High']])

   Rating
0     1.0
1     2.0
2     0.0
3     2.0
4     1.0